services:

  node:
    build: .
    container_name: HosBank
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: hosbank
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PW: ${POSTGRES_PW}
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npm run db:setup && npm start"


  postgres:
    image: postgres:17-alpine
    container_name: hosbank-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: hosbank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10


  pgadmin:
    image: dpage/pgadmin4:snapshot
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "hosbank@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PW}
    ports:
      - "5555:80"
    depends_on:
      - postgres

